version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork
  python_app:
    build:
      context: .
    container_name: python_app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - mynetwork
volumes:
  mongo-data:
networks:
  mynetwork:
